version: '2'

services:
  formchecker:
    image: registry.diginfra.net/tsd/cmdi-form_checker:1.0
    container_name: formchecker
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.formchecker.entrypoints=http"
      - "traefik.http.routers.formchecker.rule=Host(`cmdiform.sd.di.huc.knaw.nl`)"
    environment:
      - 'APPLICATION_NAME=CMDI Form Checker'
      - CMDI_URI=https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/1.x/profiles/[PROFILE_ID]/xml
      - HOST_URI=https://cmdiform.sd.di.huc.knaw.nl/
    volumes:
      - cmdi_tweaks:/var/www/html/data/tweaks
    networks:
      - traefik-public

volumes:
  cmdi_tweaks:
    external: true

networks:
  traefik-public:
    external: true